/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Averages {
  'totalEntries' : bigint,
  'questionAverages' : Array<number>,
}
export type Group = { 'groupA' : null } |
  { 'groupB' : null };
export interface Response { 'scores' : Array<bigint>, 'group' : Group }
export interface _SERVICE {
  'getAllResponses' : ActorMethod<[], Array<Response>>,
  'getAveragesByGroup' : ActorMethod<[Group], Averages>,
  'getResponsesByGroup' : ActorMethod<[Group], Array<Response>>,
  'submitResponse' : ActorMethod<[Group, Array<bigint>], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];