/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Group = IDL.Variant({ 'groupA' : IDL.Null, 'groupB' : IDL.Null });
export const Response = IDL.Record({
  'scores' : IDL.Vec(IDL.Nat),
  'group' : Group,
});
export const Averages = IDL.Record({
  'totalEntries' : IDL.Nat,
  'questionAverages' : IDL.Vec(IDL.Float64),
});

export const idlService = IDL.Service({
  'getAllResponses' : IDL.Func([], [IDL.Vec(Response)], ['query']),
  'getAveragesByGroup' : IDL.Func([Group], [Averages], ['query']),
  'getResponsesByGroup' : IDL.Func([Group], [IDL.Vec(Response)], ['query']),
  'submitResponse' : IDL.Func([Group, IDL.Vec(IDL.Nat)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Group = IDL.Variant({ 'groupA' : IDL.Null, 'groupB' : IDL.Null });
  const Response = IDL.Record({ 'scores' : IDL.Vec(IDL.Nat), 'group' : Group });
  const Averages = IDL.Record({
    'totalEntries' : IDL.Nat,
    'questionAverages' : IDL.Vec(IDL.Float64),
  });
  
  return IDL.Service({
    'getAllResponses' : IDL.Func([], [IDL.Vec(Response)], ['query']),
    'getAveragesByGroup' : IDL.Func([Group], [Averages], ['query']),
    'getResponsesByGroup' : IDL.Func([Group], [IDL.Vec(Response)], ['query']),
    'submitResponse' : IDL.Func([Group, IDL.Vec(IDL.Nat)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };